worlds:
    base:
        folder: ''
        suffixes:
        - ''
    survival_end:
        folder: main_end_normal_1-7_15-12-2013
        inheritances:
        - survival_overworld
    survival_nether:
        folder: main_nether_normal_1-7_15-12-2013
        inheritances:
        - survival_overworld
    survival_overworld:
        folder: main_survival_normal_1-7_14-12-2013
        inheritances:
        - base
        suffixes:
        - survival
    survival_new:
        folder: main_survival_normal_1-8_17-01-2015_2
        inheritances:
        - survival_overworld
    pvp_end:
        folder: war_end_pvp_1-7_15-12-2013
        inheritances:
        - pvp_overworld
    pvp_nether:
        folder: war_nether_pvp_1-7_15-12-2013
        inheritances:
        - pvp_overworld
    pvp_overworld:
        folder: war_survival_pvp_1-7_15-12-2013
        inheritances:
        - survival_overworld
    creative_flatland:
        folder: main_creative_flatland_1-6_migrated
        inheritances:
        - base
        suffixes:
        - creative
    creative_terrain:
        folder: main_creative_terrain_1-6_migrated
        inheritances:
        - creative_flatland
    creative_hub:
        folder: main_creative_hub_1-6_migrated
        inheritances:
        - creative_flatland
    creative_tettura:
        folder: main_creative_tettura_1-6_migrated
        inheritances:
        - creative_flatland
    theblock:
        folder: minigame_creative_block_1-6_migrated
        inheritances:
        - creative_flatland

groups:
    Guest:
    - default
    Builder:
    - builder
    Trusted:
    - trusted
    Donator:
    - donator
    Guard:
    - guard
    Moderator:
    - mod
    Admin:
    - admin
