worlds:
    base:
        folder: ''
        suffixes:
        - ''
    survival_end:
        folder: main_end_normal_1-7_15-12-2013
        inheritance:
        - survival_overworld
        suffixes:
        - end
    survival_nether:
        folder: main_nether_normal_1-7_15-12-2013
        inheritance:
        - survival_overworld
    survival_overworld:
        folder: main_survival_normal_1-7_14-12-2013
        inheritance:
        - base
        suffixes:
        - survival
    survival_new_end:
        folder: main_end_normal_1-10
        inheritance:
        - survival_overworld
        suffixes:
        - end
    survival_new_nether:
        folder: main_nether_normal_1-10
        inheritance:
        - survival_overworld
    survival_new_overworld:
        folder: main_survival_normal_1-10
        inheritance:
        - survival_overworld
    creative_flatland:
        folder: main_creative_flatland_1-6_migrated
        inheritance:
        - base
        suffixes:
        - creative
    creative_terrain:
        folder: main_creative_terrain_1-6_migrated
        inheritance:
        - creative_flatland

groups:
    Guest:
    - default
    Builder:
    - builder
    Trusted:
    - trusted
    Donator:
    - donator
    Guard:
    - guard
    Moderator:
    - mod
    Admin:
    - admin
